app = "vercel-test-icy-snow-2326"

[env]
PORT = "8000"  # Ensure your app runs on port 8000
PYTHONPATH = "/app"

[build]
dockerfile = "Dockerfile"

[deploy]
# Removed `release_command` because it's unnecessary for a running server

[experimental]
auto_rollback = true  # Automatically rollback if deployment fails

[[services]]
internal_port = 8000  # Ensure this matches the port FastAPI is listening on
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80  # Publicly accessible HTTP port (maps to internal 8000)

[[services.ports]]
handlers = ["tls"]
port = 443  # Enable HTTPS

