# fly.toml app configuration file generated for core-api-green-bird-4902 on 2025-03-06T21:10:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'core-api-green-bird-4902'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
