# fly.toml app configuration file generated for text-analysis-api on 2025-03-06T21:11:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'knowledge-graph-broken-surf-6085'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8002
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
